# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - odin test lasiodin/ -o:speed -debug -show-timings -define:ODIN_TEST_THREADS=7 -define:ODIN_TEST_RANDOM_SEED=102
    silent: false
    aliases:
      - t

  build_lasloading:
    cmds:
      - odin build ./examples/load_and_print_info -out:./bin/load_and_print_info.exe -o:speed
    silent: false
    method: none
    aliases:
      - ex1b
    generates:
      - ./bin/load_and_print_info.exe
    sources:
      - ./examples/load_and_print_info/

  lasloading:
    cmds:
      - ./bin/load_and_print_info.exe ./assets/example_1_canadian_well_logging_society.las
    silent: false
    method: none
    aliases:
      - ex1r

  build_usage:
    cmds:
      - odin build ./examples/usage -out:./bin/usage.exe -o:speed

    silent: false
    method: none
    aliases:
      - ub
    generates:
      - ./bin/usage.exe
    sources:
      - ./lasiodin/**/*.odin
      - ./lasiodin/*.odin
      - ./examples/usage/main.odin


  usage:
    cmds:
      - ./bin/usage.exe
    silent: false
    method: none
    aliases:
      - ur
    sources:
      - ./lasiodin/**/*.odin
      - ./lasiodin/*.odin
      - ./examples/usage/main.odin


  build_las_to_csv:
    cmds:
      - odin build ./examples/las_to_csv -out:./bin/las_to_csv.exe -o:speed
    silent: true
    method: none
    aliases:
      - l2cb
    generates:
      - ./bin/las_to_csv.exe
    sources:
      - ./lasiodin/**/*.odin
      - ./lasiodin/*.odin
      - ./examples/las_to_csv/main.odin

  las_to_csv:
    deps: [build_las_to_csv]
    cmds:
      - rm ./assets/example_1_canadian_well_logging_society.csv
      - ./bin/las_to_csv.exe ./assets/example_1_canadian_well_logging_society.las ./assets/example_1_canadian_well_logging_society.csv
      - cat ./assets/example_1_canadian_well_logging_society.csv
    watch: true
    silent: true
    method: none
    aliases:
      - l2cr
    sources:
      - ./lasiodin/**/*.odin
      - ./lasiodin/*.odin
      - ./examples/las_to_csv/main.odin

